/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package JFrames;
import java.sql.*;
import Project.connectionProvider;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;



/**
 *
 * @author pkara
 */
public class addNewDonor extends javax.swing.JFrame {

    /**
     * Creates new form addNewDonor
     */
    public addNewDonor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        etEmailID = new javax.swing.JTextField();
        etCity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        etCompleteAddress = new javax.swing.JTextArea();
        cbBloodGroup = new javax.swing.JComboBox<>();
        btnSaveAddNewDonor = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnResetAddNewDonor = new javax.swing.JButton();
        btnCloseAddNewDonor = new javax.swing.JButton();
        etFullName = new javax.swing.JTextField();
        etFatherName = new javax.swing.JTextField();
        etMotherName = new javax.swing.JTextField();
        etMobilenumber = new javax.swing.JTextField();
        cbGender = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        tvDonorId = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(340, 130));
        setUndecorated(true);
        setSize(new java.awt.Dimension(700, 500));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("ADD NEW DONOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("New Donor ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Full Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, 94, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Fathers Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 94, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Mother Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 94, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Date Of Birth:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 203, 94, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Mobile No:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 94, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Gender:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 277, 94, -1));
        getContentPane().add(etEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 160, -1));
        getContentPane().add(etCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 160, -1));

        etCompleteAddress.setColumns(20);
        etCompleteAddress.setRows(5);
        jScrollPane1.setViewportView(etCompleteAddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        cbBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        cbBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBloodGroupActionPerformed(evt);
            }
        });
        getContentPane().add(cbBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 160, -1));

        btnSaveAddNewDonor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSaveAddNewDonor.setText("Save");
        btnSaveAddNewDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAddNewDonorActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveAddNewDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 330, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 314, 680, 10));

        btnResetAddNewDonor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnResetAddNewDonor.setText("Reset");
        btnResetAddNewDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetAddNewDonorActionPerformed(evt);
            }
        });
        getContentPane().add(btnResetAddNewDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 330, -1, -1));

        btnCloseAddNewDonor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCloseAddNewDonor.setText("Close");
        btnCloseAddNewDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseAddNewDonorActionPerformed(evt);
            }
        });
        getContentPane().add(btnCloseAddNewDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 330, -1, -1));
        getContentPane().add(etFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 92, 160, -1));
        getContentPane().add(etFatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 129, 160, -1));
        getContentPane().add(etMotherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 166, 160, -1));
        getContentPane().add(etMobilenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 160, -1));

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        getContentPane().add(cbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 277, 160, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Email ID:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 92, 187, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Blood Group:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 129, 187, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("City:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 166, 187, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Complete Address:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 203, 187, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 203, 160, -1));

        tvDonorId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tvDonorId.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(tvDonorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 57, 36, 17));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JFrames/BBMS ICON/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    

        
    private void btnResetAddNewDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetAddNewDonorActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new addNewDonor().setVisible(true);
    }//GEN-LAST:event_btnResetAddNewDonorActionPerformed

    private void btnCloseAddNewDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseAddNewDonorActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseAddNewDonorActionPerformed

    private void btnSaveAddNewDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAddNewDonorActionPerformed
        // TODO add your handling code here:
        String donorId=tvDonorId.getText();
        String name = etFullName.getText();
        String fatherName = etFatherName.getText();
        String motherName = etMotherName.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-YYY");
        String DOB = dateFormat.format(jDateChooser1.getDate());
        String mobileNo = etMobilenumber.getText();
        String gender = (String)cbGender.getSelectedItem();
        String emailId = etEmailID.getText();
        String bloodGroup = (String)cbBloodGroup.getSelectedItem();
        String city = etCity.getText();
        String address = etCompleteAddress.getText();
        
        
        try{
            Connection con = connectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("insert into donor values(null,'"+name+"','"+fatherName+"','"+motherName+"','"+DOB+"','"+mobileNo+"','"+gender+"','"+emailId+"','"+bloodGroup+"','"+city+"','"+address+"')");
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            setVisible(false);
            new addNewDonor().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
            
        }
    }//GEN-LAST:event_btnSaveAddNewDonorActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
            Connection con=connectionProvider.getCon();
            Statement st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery("select max(donorId) from donor");
            if(rs.first())
            {
                int id = rs.getInt(1);
                id += 1;
                String str1 = String.valueOf(id);
                tvDonorId.setText(str1);
            }
            else{
                
            } 
            
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        
        }
    }//GEN-LAST:event_formComponentShown

    private void cbBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBloodGroupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            
            new addNewDonor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseAddNewDonor;
    private javax.swing.JButton btnResetAddNewDonor;
    private javax.swing.JButton btnSaveAddNewDonor;
    private javax.swing.JComboBox<String> cbBloodGroup;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JTextField etCity;
    private javax.swing.JTextArea etCompleteAddress;
    private javax.swing.JTextField etEmailID;
    private javax.swing.JTextField etFatherName;
    private javax.swing.JTextField etFullName;
    private javax.swing.JTextField etMobilenumber;
    private javax.swing.JTextField etMotherName;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel tvDonorId;
    // End of variables declaration//GEN-END:variables
}
