/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;
import java.sql.*;
import Project.connectionProvider;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author pkara
 */
public class searchBLoodDonorBloodGroup extends javax.swing.JFrame {

    /**
     * Creates new form searchBLoodDonorBloodGroup
     */
    public searchBLoodDonorBloodGroup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        etBloodGroupSearchBloodDonor = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSearchBloodDonorBloodGroup = new javax.swing.JTable();
        btnPrintSearchBloodDonorBloodGroup = new javax.swing.JButton();
        btnCloseSearchBloodDonorBLoodGroup = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(340, 170));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Search Blood Donor(Blood Group)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 662, 10));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Blood Group:  ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        etBloodGroupSearchBloodDonor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                etBloodGroupSearchBloodDonorKeyReleased(evt);
            }
        });
        getContentPane().add(etBloodGroupSearchBloodDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 173, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 662, 10));

        tableSearchBloodDonorBloodGroup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableSearchBloodDonorBloodGroup);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 662, 330));

        btnPrintSearchBloodDonorBloodGroup.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPrintSearchBloodDonorBloodGroup.setText("Print");
        btnPrintSearchBloodDonorBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintSearchBloodDonorBloodGroupActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrintSearchBloodDonorBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        btnCloseSearchBloodDonorBLoodGroup.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCloseSearchBloodDonorBLoodGroup.setText("Close");
        btnCloseSearchBloodDonorBLoodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseSearchBloodDonorBLoodGroupActionPerformed(evt);
            }
        });
        getContentPane().add(btnCloseSearchBloodDonorBLoodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 662, 11));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JFrames/BBMS ICON/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void btnCloseSearchBloodDonorBLoodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseSearchBloodDonorBLoodGroupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseSearchBloodDonorBLoodGroupActionPerformed

    private void btnPrintSearchBloodDonorBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintSearchBloodDonorBloodGroupActionPerformed
        // TODO add your handling code here:
        try {
            tableSearchBloodDonorBloodGroup.print(JTable.PrintMode.NORMAL);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnPrintSearchBloodDonorBloodGroupActionPerformed

    private void etBloodGroupSearchBloodDonorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etBloodGroupSearchBloodDonorKeyReleased
        // TODO add your handling code here:
        String bloodgroup = etBloodGroupSearchBloodDonor.getText();
        try {
            Connection con = connectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from donor where bloodGroup like '%"+bloodgroup+"'");
            tableSearchBloodDonorBloodGroup.setAutoResizeMode(tableSearchBloodDonorBloodGroup.AUTO_RESIZE_OFF);
            tableSearchBloodDonorBloodGroup.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_etBloodGroupSearchBloodDonorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchBLoodDonorBloodGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchBLoodDonorBloodGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchBLoodDonorBloodGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchBLoodDonorBloodGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchBLoodDonorBloodGroup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseSearchBloodDonorBLoodGroup;
    private javax.swing.JButton btnPrintSearchBloodDonorBloodGroup;
    private javax.swing.JTextField etBloodGroupSearchBloodDonor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tableSearchBloodDonorBloodGroup;
    // End of variables declaration//GEN-END:variables
}
